### ISSUE TITLE
micropython 1.20, mpy files aren't running

### ISSUE THREAD

**Issue by massimosala** [pybricks/python-mpy-cross#28]
With the latest firmware MicroPython v1.20.0 on 2023-04-26
if any .py file contains native code
the mpy files built with mpy-cross-v6 don't work:

`ValueError: incompatible .mpy file 
`

The same mpy files work fine with micropython 1.19.

The problem is described here:
https://github.com/micropython/micropython/issues/11367

**Comment by dlech** [comment]
Thanks for the reminder. There is now a new `mpy-cross-v6.1` package published to PyPI based on MicroPython v1.20 that will support MPY v6.1 native modules.

https://pypi.org/project/mpy-cross-v6.1

**Comment by massimosala** [comment]
> Thanks for the reminder. There is now a new `mpy-cross-v6.1` package published to PyPI based on MicroPython v1.20 that will support MPY v6.1 native modules.
> 
> https://pypi.org/project/mpy-cross-v6.1

Thanks David, the new release solved the problem.
